instrumentation:
  - class: com.movieapi.ApiServlet
    method: getUserFavorites 
    returnOrArgument: argument_0
    addBaggage: TRUE
    type: renamespan
  - class: com.example.ClassB
    method: methodB
    returnOrArgument: return
    addBaggage: FALSE
    type: datacollector
url:
  - currentUrl: GET blah/blah
    attribute: span.url
    regEx: .* 
